/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.OldSpace.gui.internalFrame;

/**
 *
 * @author YonattanVisita
 */
public class Inventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InventarioFrame
     */
    

    
    public Inventario() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListProducts = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        dddd = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        btnAddStock = new javax.swing.JButton();
        txtAddStock = new javax.swing.JTextField();
        txtSearchProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNexPage = new javax.swing.JButton();
        btnStarPage = new javax.swing.JButton();
        txtNumberPage = new javax.swing.JTextField();
        btnBackPage = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNewProvider = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNewProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNewCategory = new javax.swing.JButton();
        btnUpdateProduct = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(null);
        setResizable(true);
        setTitle("Invetario");
        setMaximumSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 670, 10));

        jLabel1.setText("Inventario ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, -1));

        jLabel3.setText("Nombre Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, -1));

        jLabel4.setText("Existencia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, -1));

        tblListProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListProducts);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 344, 700, 232));

        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 186, 138));

        dddd.setText("Modificar Producto");
        dddd.setToolTipText("");
        getContentPane().add(dddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 344, -1, -1));

        btnDeleteProduct.setText("Eliminar Producto");
        getContentPane().add(btnDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 388, 138, -1));

        btnAddStock.setText("Agregar");
        getContentPane().add(btnAddStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 107, -1));
        getContentPane().add(txtAddStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 170, -1));
        getContentPane().add(txtSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 371, -1));

        jLabel5.setText("Ingresar al inventario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel6.setText("Buscar Producto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        btnNexPage.setText(">");
        getContentPane().add(btnNexPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 582, -1, -1));

        btnStarPage.setText("|<");
        getContentPane().add(btnStarPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 582, -1, -1));
        getContentPane().add(txtNumberPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 582, 27, -1));

        btnBackPage.setText("<");
        getContentPane().add(btnBackPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 582, -1, -1));

        jLabel7.setText("Pagina :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 590, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnNewProvider.setBackground(new java.awt.Color(102, 51, 255));
        btnNewProvider.setForeground(new java.awt.Color(255, 255, 255));
        btnNewProvider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OldSpace/gui/imagenes/AddProvider_96px.png"))); // NOI18N
        btnNewProvider.setBorder(null);
        btnNewProvider.setBorderPainted(false);
        btnNewProvider.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewProvider, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewProvider)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 130, 110));

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnNewProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnNewProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OldSpace/gui/imagenes/AddProduct_96px.png"))); // NOI18N
        btnNewProduct.setToolTipText("Agregar Producto");
        btnNewProduct.setBorder(null);
        btnNewProduct.setBorderPainted(false);
        btnNewProduct.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewProduct)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 110));

        jPanel3.setBackground(new java.awt.Color(102, 51, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        btnNewCategory.setBackground(new java.awt.Color(102, 51, 255));
        btnNewCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnNewCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/OldSpace/gui/imagenes/AddCategory_96px.png"))); // NOI18N
        btnNewCategory.setBorder(null);
        btnNewCategory.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewCategory)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 110));

        btnUpdateProduct.setBackground(new java.awt.Color(0, 51, 153));
        btnUpdateProduct.setBorder(null);
        btnUpdateProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateProduct.setText("Modificar Producto");
        btnUpdateProduct.setBorderPainted(false);
        btnUpdateProduct.setContentAreaFilled(false);
        getContentPane().add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lblImageMouseClicked

    private void tblListProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListProductsMouseClicked
       
    }//GEN-LAST:event_tblListProductsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddStock;
    public javax.swing.JButton btnBackPage;
    public javax.swing.JButton btnDeleteProduct;
    public javax.swing.JButton btnNewCategory;
    public javax.swing.JButton btnNewProduct;
    public javax.swing.JButton btnNewProvider;
    public javax.swing.JButton btnNexPage;
    public javax.swing.JButton btnStarPage;
    public principal.MaterialButton btnUpdateProduct;
    public javax.swing.JButton dddd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblImage;
    public javax.swing.JTable tblListProducts;
    public javax.swing.JTextField txtAddStock;
    public javax.swing.JTextField txtCod;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtNumberPage;
    public javax.swing.JTextField txtSearchProduct;
    public javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
